### ISSUE TITLE
你好，请问下带有参数请求的POST接口可以做嘛

### ISSUE THREAD

**Issue by cfy3133** [TheCoolQATeam/online-inspection-tracker#1]

**Comment by zdx0122** [comment]
1. 目前仅支持H5页面的巡检，暂时未做接口层级的巡检，我们内部版本也一样没做，巡检是在线上环境的操作，post会产生大量非正常业务数据，影响需要控制。

2. 可行性上来说，是可以做的；

3. 可以详细说下使用场景吗？

4. 如果有很多人有这个这个需求，我们可以统一开发支持下，也欢迎提pr
